version: '3'

volumes:
  db:
  redis:

services:
  db:
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    container_name: 'postgres'
    volumes:
      - db:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: Postgres@123
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: localhost

  crud:
    container_name: crud
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db
    command: ["npm", "run", "start:dev"]

  redis: 
    image: redis:lasted
    ports:
      - 6379:6379
    container_name: 'redis'
    volumes:
      - redis:/var/lib/redis